version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          max_command_length: 100
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: ms-teams-notifier
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review]
          filters: *filters
