version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0.4
  ms-teams-notifier: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: wasikuss/ms-teams-notifier
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          requires:
            - orb-tools/pack
          filters: *release-filters
